name: spectrallock
description: Rosetta spectral analysis. Same lenses as Aziel Corpus Library OCR.
publish_to: "none"
version: 0.3.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
